version: '3.8'
services:
  table-order-service:
    restart: on-failure
    build: .
    image: table-order-service:latest
    container_name: table-order-service  # 사용자 정의 이름
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://dh-project.mooo.com:3306/table-order
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    volumes:
      - - C:/images:/images # DDNS 서버의 노트북 이미지 저장소 지정 (도커 통신을 위한)