version: '3.8'
services:
  table-order-service:
    restart: on-failure
    build: .
    image: table-order-service:latest
    container_name: table-order-service  # 사용자 정의 이름
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://toyproject.cv0qaskygtdb.ap-northeast-2.rds.amazonaws.com:3306/table-order
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234!
