server:
  port: 8081
  servlet:
    context-path: /table-order

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/table-order
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG

# 로컬 테스트 시 dir, imageUrl을 로컬로 변경해야함. 현재 DDNS의 노트북에 대한 정의임.
file:
  dir: C:\images  #/Users/sondonghwan/Desktop/images
  imageUrl: http://dh-project.mooo.com:8081/table-order/image #http://localhost:8081/table-order/image