server:
  port: 8081
  servlet:
    context-path: /table-order

spring:
  datasource:
    url: jdbc:mysql://dh-project.mooo.com:3306/table-order
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
