server:
  port: 8080
  servlet:
    context-path: /table-order

spring:
  datasource:
    url: jdbc:mysql://toyproject.cv0qaskygtdb.ap-northeast-2.rds.amazonaws.com:3306/table-order
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234!
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
