server:
  port: 8081
  servlet:
    context-path: /table-order

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/table-order
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        show_sql: false
        format_sql: true
        highlight_sql: true

logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm.jdbc.bind: TRACE

jwt:
  secret: fM6xV5jHs2Q3tLp8Dz4RkYz1Wq9sZtE7Bc8NnQj3FgWkTsHqJvR
  access-token-expire-time: 43200000
  refresh-token-expire-time: 86400

# 로컬 테스트 시 dir, imageUrl을 로컬로 변경해야함. 현재는 dir은 도커의 디렉토리고, url은 DDNS이다.
file:
  dir: /images  #/Users/sondonghwan/Desktop/images
  imageUrl: http://dh-project.mooo.com:8081/table-order/image #http://localhost:8081/table-order/image